name: Run DarkIT Model 🚀

on:
  workflow_dispatch: # يتيح لك تشغيله يدوياً من واجهة جيتهاب

jobs:
  run-ai:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install llama-cpp-python

    - name: Run Model
      run: python chat.py
